export const REQUESTSTART = 'REQUESTSTART'
export const FAILUREMSG = 'FAILUREMSG'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SNSLOGINS_SUCCESS = 'SNSLOGINS_SUCCESS'
/*用户信息类型*/
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const NICKNAME = 'NICKNAME'
export const MOBILE = 'MOBILE'
export const MOBILE_CAPTCHA = 'MOBILE_CAPTCHA'

//记账详情明细类型
export const DETAIL_SUCCESS = 'DETAIL_SUCCESS'
export const DETAIL_SUM_SUCCESS = 'DETAIL_SUCCESS'
export const DETAIL_LIST_SUCCESS = 'DETAIL_LIST_SUCCESS'
export const DETAIL_ID = 'DETAIL_ID'
export const DETAIL_CLASSID = 'DETAIL_CLASSID'
export const DETAIL_ACCOUNTID = 'DETAIL_ACCOUNTID'
export const DETAIL_TYPE = 'DETAIL_TYPE'
export const DETAIL_CONTENT = 'DETAIL_CONTENT'
export const DETAIL_MONEY = 'DETAIL_MONEY'
export const DETAIL_CREATEDATE = 'DETAIL_CREATEDATE'
export const DETAIL_LAST_ID = 'DETAIL_LAST_ID'

export const ACCOUNT_LIST_SUCCESS = 'ACCOUNT_LIST_SUCCESS'

//时间改变类型
export const TIME_CHANGE = 'TIME_CHANGE'

//类别
export const CATEGORY_DATA_SUCCESS = 'CATEGORY_DATA_SUCCESS'
export const CATEGORY_DATA_LIST_SUCCESS = 'CATEGORY_DATA_LIST_SUCCESS'
export const CATEGORY_DATA_CHART_SUCCESS = 'CATEGORY_DATA_CHART_SUCCESS'
export const CATEGORY_SELECTLABEL = 'CATEGORY_SELECTLABEL'
export const CATEGORY_PAYORINCOME = 'CATEGORY_PAYORINCOME'
export const CATEGORY_NAME = 'CATEGORY_NAME'
export const CATEGORY_ID = 'CATEGORY_ID'
export const CATEGORY_INIT = 'CATEGORY_INIT'
export const CATEGORY_TYPE = 'CATEGORY_TYPE'
export const CATEGORY_MONEY = 'CATEGORY_MONEY'

//切换菜单初始化
export const NAVITEMS_INIT = 'NAVITEMS_INIT' 
